/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/ME109.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.Material}
        position={[0, 0.04, 2.35]}
        rotation={[Math.PI / 2, -1.08, 0]}
        scale={[0.05, 0.03, 0.05]}
      />
    </group>
  );
}

useGLTF.preload("/ME109.gltf");
